### ISSUE TITLE
Act 2 Infografía Ana Kimberly Hernández Pérez 1ro B

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-2-infografia-Anakimberly#1]
![Infografía algunas cosas que puedes hacer en tu tiempo libre divertido ilustrado sticker azul](https://user-images.githubusercontent.com/112224202/187728499-95ab18c5-f206-4e6f-803e-f94125741b51.png)

**Comment by AmeliReyesHernandez** [comment]
17.8 de 20

**Comment by AmeliReyesHernandez** [comment]
17.6 de 20

**Comment by josealfredo79** [comment]
c
